### ISSUE TITLE
Split Screen

### ISSUE THREAD

**Issue by Detril** [MarvellousSoft/hooksharks#11]

**Comment by Detril** [comment]
It is "done". It currently doesn't work with other features (like ScreenShake) well. I'll leave the Issue open until an _ultimatum_ where we either continue work on this or decide it will not be in the game.

**Comment by ArthurTui** [comment]
I think we have to work on having the racing mode playable in its final state as soon as possible so we can decide which features will be necessary at last.

**Comment by rilifon** [comment]
Splitscreen was dropped for the time being
