### ISSUE TITLE
Make executable's icon the same as game's icon

### ISSUE THREAD

**Issue by Detril** [MarvellousSoft/hooksharks#167]
Currently, the executable's icon is just the Godot Engine's icon.

**Comment by LuizGyro** [comment]
For Linux and Mac, Godot automatically does this for us. As for Windows, we need to set it in the export settings under Application -> Icon under the Options tab,

**Comment by ArthurTui** [comment]
https://docs.godotengine.org/en/3.1/getting_started/workflow/export/changing_application_icon_for_windows.html
