### ISSUE TITLE
Player's Timer are unneeded?

### ISSUE THREAD

**Issue by Detril** [MarvellousSoft/hooksharks#27]
Could ParticleTimer's and AnimationTimer's uses be subistituded with signals from Particles2D and AnimationPlayer?

**Comment by ArthurTui** [comment]
For the AnimationPlayer yes, but Particles don't have signals (except from the classes it inherits, maybe one of them can be useful in this case) so what I did when I fixed the hook clink particles was to get_tree.create_timer with a duration of the particles' lifetime/speed_scale, that can be a solution.
