### ISSUE TITLE
Draw only happens when the two players collide

### ISSUE THREAD

**Issue by ArthurTui** [MarvellousSoft/hooksharks#32]
Should also happen when both die at the same time through other means.

**Comment by Detril** [comment]
Do both players die at the same time through other means in real gameplay?

**Comment by rilifon** [comment]
They hit the wall in the same frame. Happens a lot when testing since the
input is duplicated for both players, but couldn't happen in a normal game
occasionally

Em seg, 11 de fev de 2019 18:26, Andre Ferrari Moukarzel <
notifications@github.com> escreveu:

**Comment by ArthurTui** [comment]
Solved by changing the way the win condition check to this:

When a player dies and is removed, the game checks on the next frame (via call_deferred) how many players are left alive. If only one is, he is the winner; if none are, a draw happens; otherwise the game continues.
