### ISSUE TITLE
Should movement of sharks be not relative?

### ISSUE THREAD

**Issue by Detril** [MarvellousSoft/hooksharks#35]
As of now, the user can choose to turn the shark to right or left of it's relative position.

Should this movement be not relative to the position to the shark? As in, the shark would turn until it is directed in the angle pointed by the analog stick, instead of the analog stick being essentially another arrow input for turning to a relative left or right.

Maybe even both controls could be implemented, with the d-pad being as it is now and the analog stick being non-relative. Or the user could choose it's prefered control.

**Comment by rilifon** [comment]
We can change and see how it feels, but I think that from my experience
with tank-like movement in topdown games, it feels a bit weird when is not
relative

Em seg, 11 de fev de 2019 18:19, Andre Ferrari Moukarzel <
notifications@github.com> escreveu:

**Comment by rilifon** [comment]
But ideally we could make this an option on the character select screen,
and each player chooses his prefered control, as you mentioned.

Em seg, 11 de fev de 2019 às 23:13, Ricardo F <pudimdefrutas@gmail.com>
escreveu:

**Comment by ArthurTui** [comment]
I'd like it to be an option too, maybe it would even make sense to have customizable key bindings alongside it in the character selection screen, but both those things shouldn't be a priority. 

What we can do now is test both ways with more people and stick with whichever one is preferred by most.

**Comment by rilifon** [comment]
Added different types of movement via 4e1ac9325423e188f046864ab1116e35f05efedf
