### ISSUE TITLE
Screen shake doesn't work with SplitScreen

### ISSUE THREAD

**Issue by Detril** [MarvellousSoft/hooksharks#42]
Screen shake doesn't work with split screens because Game.gd tries to get the cameras before they are instanciated.

It could be fixed by adding a yield in Game.gd, where it waits for a signal that the Splitscreen scene is ready to get cameras, or other modifications directly in Race.gd could be more appropriate

**Comment by rilifon** [comment]
For now we are dropping splitscreen
