### ISSUE TITLE
Should the hook "remember" the last direction you aimed to?

### ISSUE THREAD

**Issue by Detril** [MarvellousSoft/hooksharks#89]
It was suggested on Lets Play that when a player lets go of the right analog stick (the one which aims the hook) and shoots the hook, the hook should go in the direction last aimed instead of going in the direction the shark is facing.

**Comment by LuizGyro** [comment]
Unless the arrow is constantly being shown, I think it would be more confusing than as it is now.

**Comment by ArthurTui** [comment]
I prefer the way it is now. I feel like it's way more intuitive to just shoot forward when you're not aiming.

**Comment by Detril** [comment]
I think the player's confusion would be solved if we changed the representation of the aiming direction. 

Instead of an arrow, the shark rider should be constantly be holding the hook in the direction it is being aimed, and that hook would default to a neutral position when the player is not aiming at anything.
